name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_osm_plugin: ^1.0.5
  flutter_secure_storage: ^4.2.1
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
