name: weather_app
description: "Weather App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_osm_plugin: ^1.0.5
  flutter_secure_storage: ^4.2.1
  geolocator: ^12.0.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  jiffy: ^6.3.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  result_type: ^0.2.0
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/weather_images/